import comments from "@eslint-community/eslint-plugin-eslint-comments/configs";
import eslintReact from "@eslint-react/eslint-plugin";
import js from "@eslint/js";
import tsParser from "@typescript-eslint/parser";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import pluginReact from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import { defineConfig } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig([
  {
    ignores: ["dist/", "node_modules/", "coverage/", "dockerbuild/", "server/", "webpack/", "postcss.config.js"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  comments.recommended,
  pluginReact.configs.flat.recommended,
  reactHooks.configs["recommended-latest"],
  eslintReact.configs["recommended-typescript"],
  {
    files: ["client/**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}", "server/**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    languageOptions: {
      globals: globals.browser,
      parser: tsParser,
      parserOptions: {
        project: "./tsconfig.json",
        sourceType: "module",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "func-style": ["error", "declaration", { allowArrowFunctions: true }],
      "no-restricted-exports": ["error", { restrictDefaultExports: { direct: true } }],
      "no-restricted-imports": ["error", { patterns: ["../../*"] }],
      "no-restricted-syntax": [
        "error",
        {
          selector: ":matches(PropertyDefinition, MethodDefinition) > PrivateIdentifier.key",
          message: "Use `private` instead of '#'",
        },
      ],
      "prefer-const": ["error", { destructuring: "all" }],
      "@eslint-community/eslint-comments/require-description": ["error", { ignore: ["eslint-enable"] }],
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-expect-error": "allow-with-description",
          "ts-ignore": "allow-with-description",
          "ts-check": false,
          "ts-nocheck": false,
        },
      ],
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      // "@typescript-eslint/no-floating-promises": ["error"], // AR: we have async context methods with error handling inside
      "@typescript-eslint/no-unused-expressions": "off",
      "@typescript-eslint/no-unused-vars": ["error", { args: "none", ignoreRestSiblings: true }],
      "@typescript-eslint/return-await": ["error", "in-try-catch"],
      "react/react-in-jsx-scope": "off",
      "react/no-unescaped-entities": "off",
      "react/void-dom-elements-no-children": "error",
      "react/style-prop-object": "error",
      "react/boolean-prop-naming": "error",
      "react/static-property-placement": "error",
      "react/state-in-constructor": "error",
      "react/sort-prop-types": "error",
      "react/sort-default-props": "error",
      "react/sort-comp": "error",
      "react/self-closing-comp": "error",
      "react/require-optimization": "error",
      "react/prefer-stateless-function": "error",
      "react/prefer-read-only-props": "error",
      "react/prefer-es6-class": "error",
      "react/no-will-update-set-state": "error",
      "react/no-unused-state": "error",
      "react/no-unused-prop-types": "error",
      "react/no-unused-class-component-methods": "error",
      "react/no-unstable-nested-components": "error",
      "react/no-typos": "error",
      "react/no-this-in-sfc": "error",
      "react/no-set-state": "error",
      "react/no-redundant-should-component-update": "error",
      "react/no-object-type-as-default-prop": "error",
      "react/no-namespace": "error",
      "react/no-invalid-html-attribute": "error",
      "react/no-did-update-set-state": "error",
      "react/no-did-mount-set-state": "error",
      "react/no-arrow-function-lifecycle": "error",
      "react/no-array-index-key": "error",
      "react/no-adjacent-inline-elements": "error",
      "react/no-access-state-in-setstate": "error",
      "react/jsx-wrap-multilines": "error",
      "react/jsx-tag-spacing": "error",
      "react/jsx-space-before-closing": "error",
      "react/jsx-sort-props": "error",
      "react/jsx-props-no-spreading": "error",
      "react/jsx-props-no-spread-multi": "error",
      "react/jsx-props-no-multi-spaces": "error",
      "react/jsx-pascal-case": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/jsx-no-script-url": "error",
      "react/jsx-no-leaked-render": "error",
      "react/jsx-max-depth": ["error", { max: 4 }],
      "react/jsx-indent-props": ["error", 2],
      "react/jsx-indent": ["error", 2],
      "react/jsx-handler-names": "error",
      "react/jsx-equals-spacing": [2, "never"],
      "react/jsx-curly-spacing": "error",
      "react/jsx-curly-newline": "error",
      "react/jsx-curly-brace-presence": "error",
      "react/jsx-closing-tag-location": "error",
      "react/jsx-boolean-value": ["error", "always"],
      "react/jsx-closing-bracket-location": ["error", "after-props"],
      "react/iframe-missing-sandbox": "error",
      "react/hook-use-state": "error",
      "react/forward-ref-uses-ref": "error",
      "react/forbid-prop-types": "error",
      "react/forbid-foreign-prop-types": "error",
      "react/destructuring-assignment": "error",
      "react/default-props-match-prop-types": "error",
      "react/checked-requires-onchange-or-readonly": "error",
      "react-hooks/exhaustive-deps": "off", // Off, we decided not to use this rule as it does not suites us in all cases
      "@eslint-react/avoid-shorthand-boolean": "error",
      "@eslint-react/avoid-shorthand-fragment": "error",
      "@eslint-react/no-useless-fragment": "error",
      "@eslint-react/no-useless-forward-ref": "error",
      "@eslint-react/no-unused-state": "error",
      "@eslint-react/no-unused-class-component-members": "error",
      "@eslint-react/no-unstable-default-props": "error",
      "@eslint-react/no-unstable-context-value": "off", // Off because we use React Compiler
      "@eslint-react/no-unsafe-component-will-update": "error",
      "@eslint-react/no-unsafe-component-will-receive-props": "error",
      "@eslint-react/no-unsafe-component-will-mount": "error",
      "@eslint-react/no-string-refs": "error",
      "@eslint-react/no-set-state-in-component-will-update": "error",
      "@eslint-react/no-set-state-in-component-did-update": "error",
      "@eslint-react/no-set-state-in-component-did-mount": "error",
      "@eslint-react/no-redundant-should-component-update": "error",
      "@eslint-react/no-prop-types": "error",
      "@eslint-react/no-nested-lazy-component-declarations": "error",
      "@eslint-react/no-nested-component-definitions": "error",
      "@eslint-react/no-misused-capture-owner-stack": "error",
      "@eslint-react/no-missing-key": "error",
      "@eslint-react/no-implicit-key": "error",
      "@eslint-react/no-duplicate-key": "error",
      "@eslint-react/no-direct-mutation-state": "error",
      "@eslint-react/no-default-props": "error",
      "@eslint-react/no-create-ref": "error",
      "@eslint-react/no-component-will-update": "error",
      "@eslint-react/no-component-will-receive-props": "error",
      "@eslint-react/no-component-will-mount": "error",
      "@eslint-react/no-comment-textnodes": "error",
      "@eslint-react/no-clone-element": "error",
      "@eslint-react/no-class-component": "error",
      "@eslint-react/no-children-to-array": "error",
      "@eslint-react/no-children-prop": "error",
      "@eslint-react/no-children-only": "error",
      "@eslint-react/no-children-map": "error",
      "@eslint-react/no-children-for-each": "error",
      "@eslint-react/no-children-count": "error",
      "@eslint-react/no-array-index-key": "error",
      "@eslint-react/no-access-state-in-setstate": "error",
      "@eslint-react/jsx-uses-vars": "error",
      "@eslint-react/jsx-no-undef": "error",
      "@eslint-react/jsx-no-iife": "error",
      "@eslint-react/jsx-no-duplicate-props": "error",
      "@eslint-react/jsx-key-before-spread": "error",
      "@eslint-react/dom/no-dangerously-set-innerhtml": "off",
      "@eslint-react/dom/no-dangerously-set-innerhtml-with-children": "error",
      "@eslint-react/dom/no-find-dom-node": "error",
      "@eslint-react/dom/no-flush-sync": "error",
      "@eslint-react/dom/no-hydrate": "error",
      "@eslint-react/dom/no-missing-button-type": "error",
      "@eslint-react/dom/no-missing-iframe-sandbox": "error",
      "@eslint-react/dom/no-namespace": "error",
      "@eslint-react/dom/no-render": "error",
      "@eslint-react/dom/no-render-return-value": "error",
      "@eslint-react/dom/no-script-url": "error",
      "@eslint-react/dom/no-void-elements-with-children": "error",
      "@eslint-react/dom/no-use-form-state": "error",
      "@eslint-react/dom/no-unsafe-target-blank": "error",
      "@eslint-react/dom/no-unsafe-iframe-sandbox": "error",
      "@eslint-react/dom/no-unknown-property": "error",
      "@eslint-react/web-api/no-leaked-timeout": "error",
      "@eslint-react/web-api/no-leaked-resize-observer": "error",
      "@eslint-react/web-api/no-leaked-interval": "error",
      "@eslint-react/web-api/no-leaked-event-listener": "error",
      "@eslint-react/hooks-extra/prefer-use-state-lazy-initialization": "error",
      "@eslint-react/hooks-extra/no-unnecessary-use-prefix": "error",
      "@eslint-react/naming-convention/context-name": "error",
      "@eslint-react/naming-convention/component-name": "error",
    },
  },
  // Prettier compatibility configuration (MUST BE LAST)
  // This disables ESLint rules that would conflict with Prettier formatting and adds prettier rules
  eslintPluginPrettierRecommended,
]);
